openapi: 3.0.3
info:
  version: 1.0.0
  title: NEO API
  description: |
    This API will allow you to prompt our Azure OpenAI instance which serves our NEO internal tool.
  contact:
    email: l.leprestre@groupeonepoint.com
servers:
  - description: Environment PREPROD
    url: https://neoback.azurewebsites.net
paths:
  /azureai:
    post:
      summary: Prompt our instance
      description: |
        Get a response from our instance
      tags:
        - Azure OpenAI
      operationId: createCompany
      security:
        - bearerAuth: []  # Reference the security scheme name here
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aiRequest:
                  type: string
                  example: "Bonjour Neo"
        description: The request body for the AI prompt
      responses:
        '200':
          description: Response Generated by Azure OpenAI
          headers:
            Content-Language:
              $ref: '#/components/headers/Content-Language'
          content:
            application/json:
              schema:
                type: string  # Change the response schema to a string
              example: "Comment puis-je vous aider aujourd'hui?"
        '400':
          $ref: '#/components/responses/Error-400'
        '401':
          $ref: '#/components/responses/Error-401'
        '403':
          $ref: '#/components/responses/Error-403'
components:
  responses:
    Error-400:
      description: Bad request
      content:
        application/json:
          schema:
            oneOf:  # Use oneOf to specify multiple response types
              - $ref: '#/components/schemas/APIErrorInvalidBody'
              - $ref: '#/components/schemas/APIErrorInvalidQueryString'
          examples:
            invalidBody:
              value:
                type: "invalid-body"
                title: "One or more validation errors occurred in the body"
                detail: "Unexpected token at x position"
                status: 400
                instance: "/azureai"
            invalidQueryString:
              value:
                type: "invalid-query-string"
                title: "One or more validation errors occurred in the query string"
                detail: "Unexpected token at x position"
                status: 400
                instance: "/azureai"
    Error-401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
          example:
            type: "unauthorized"
            title: "The token is invalid to access the resources requested"
            detail: "There is no token in the authorization header"
            status: 401
            instance: "/azureai"
    Error-403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/APIError'
          example:
            httpCode: 403
            url: /my-called-URL
            errorDate: 2019-08-10T17:47:48983Z
            fishtag: oFWPMTAWoz4
            messages:
              - code: forbidden
                message: Forbidden access
  examples:
    Content-Range:
      value:
        0-14/15
    Content-Language:
      value:
        EN
  headers:
    Content-Range:
      description: Offset - End index / (Global number of items matching the search)
      schema:
        type: string
      example: 0-14/15
    Content-Language:
      description: Code iso of the content language
      schema:
        type: string
      example: EN
  schemas:
    APIError:
      type: object
      description: |-
        Definition of the standard API error message structure.
        Used for almost all error codes.
      properties:
        httpCode:
          type: integer
          description: HTTP status code
          enum:
            - 400
            - 401
            - 403
            - 404
            - 429
            - 500
            - 503
          format: int32
          example: 500
        url:
          type: string
          description: Called url
          example: /my-resource
        errorDate:
          type: string
          description: Error creation date
          format: string
          example: '2021-09-21T08:11:03.496Z'
        messages:
          type: array
          items:
            type: object
            description: |-
              Definition of the standard API message structure.
              Used for all responses excepted the 2XX code response.
            properties:
              code:
                type: string
                description: Short functional error code
                example: missing_param
              message:
                type: string
                description: Error detail
                example: '<XXX> : Missing parameter'
            required:
              - code
              - message
      required:
        - httpCode
        - url
    APIResponse:
      type: object
      description: |-
        Definition of the standard API response structure.
        Used for successful responses.
      properties:
        httpCode:
          type: integer
          description: HTTP status code
          enum:
            - 200
          format: int32
          example: 200
        url:
          type: string
          description: Called url
          example: /azureai
      required:
        - httpCode
        - url
    APIErrorInvalidBody:
      type: object
      properties:
        type:
          type: string
          example: "invalid-body"
        title:
          type: string
          example: "One or more validation errors occurred in the body"
        detail:
          type: string
          example: "Unexpected token at x position"
        status:
          type: integer
          example: 400
        instance:
          type: string
          example: "/azureai"
      required:
        - type
        - title
        - detail
        - status
        - instance
    APIErrorInvalidQueryString:
      type: object
      properties:
        type:
          type: string
          example: "invalid-query-string"
        title:
          type: string
          example: "One or more validation errors occurred in the query string"
        detail:
          type: string
          example: "Unexpected token at x position"
        status:
          type: integer
          example: 400
        instance:
          type: string
          example: "/azureai"
      required:
        - type
        - title
        - detail
        - status
        - instance
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
